# Generated by Django 3.2.6 on 2021-08-07 07:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ArticleNation', '0006_alter_article_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='likes',
            field=models.ManyToManyField(default=0, related_name='blogpost', to=settings.AUTH_USER_MODEL),
        ),
    ]
